# Generated by Django 5.2.5 on 2025-09-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_blogpost_featured_image_teammember_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_type', models.CharField(choices=[('hero_bg', 'Hero Background'), ('about_bg', 'About Background'), ('gallery_bg', 'Gallery Background'), ('testimonial_bg', 'Testimonial Background'), ('contact_bg', 'Contact Background'), ('default_service', 'Default Service Image'), ('default_team', 'Default Team Image'), ('default_testimonial', 'Default Testimonial Image')], max_length=50)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aarushi Salon', max_length=100)),
                ('site_tagline', models.CharField(default='Beauty & Wellness', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('monday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('friday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(default='10:00 AM - 6:00 PM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='theme/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='theme/')),
                ('primary_color', models.CharField(default='#e91e63', help_text='Primary color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#ff4081', help_text='Secondary color (hex code)', max_length=7)),
                ('accent_color', models.CharField(default='#f50057', help_text='Accent color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#2c2c2c', help_text='Text color (hex code)', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color (hex code)', max_length=7)),
                ('heading_font', models.CharField(default='Dancing Script', help_text='Font family for headings', max_length=100)),
                ('body_font', models.CharField(default='Work Sans', help_text='Font family for body text', max_length=100)),
                ('enable_gradients', models.BooleanField(default=True)),
                ('enable_animations', models.BooleanField(default=True)),
                ('enable_shadows', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-spa)', max_length=100)),
                ('icon_color', models.CharField(default='#e91e63', help_text='Icon color (hex code)', max_length=7)),
                ('background_color', models.CharField(default='#ff4081', help_text='Icon background color (hex code)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='salon.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Icon',
                'verbose_name_plural': 'Service Icons',
            },
        ),
    ]
