# Generated by Django 5.2.5 on 2025-09-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Your phone number (optional)', max_length=20)),
                ('service_received', models.CharField(help_text='Service you received', max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate your experience (1-5 stars)')),
                ('feedback', models.TextField(help_text='Share your experience with us')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Check to hide your name from public display')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
