# Generated by Django 5.2.5 on 2025-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='footer_color',
            field=models.CharField(default='#2c2c2c', help_text='Footer background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default theme for new users'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_color',
            field=models.CharField(default='#ffffff', help_text='Navbar background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='theme_type',
            field=models.CharField(choices=[('brown', 'Brown Theme (Current)'), ('dark', 'Dark Theme'), ('blue', 'Blue Theme'), ('pink', 'Pink/Yellow Theme')], default='brown', help_text='Predefined theme type', max_length=20),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#D2691E', help_text='Accent color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='name',
            field=models.CharField(default='Brown Theme', max_length=100),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#8B4513', help_text='Primary color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color',
            field=models.CharField(default='#A0522D', help_text='Secondary color (hex code)', max_length=7),
        ),
    ]
