# Generated by Django 5.2.5 on 2025-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_add_theme_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='footer_color',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='navbar_color',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='theme_type',
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#f50057', help_text='Accent color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='name',
            field=models.CharField(default='Default Theme', max_length=100),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#e91e63', help_text='Primary color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color',
            field=models.CharField(default='#ff4081', help_text='Secondary color (hex code)', max_length=7),
        ),
    ]
