# Generated by Django 5.2.5 on 2025-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_color_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID (e.g., GA-XXXXXXXXX)', max_length=20)),
                ('gtag_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID (e.g., G-XXXXXXXXXX)', max_length=20)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID (e.g., GTM-XXXXXXX)', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20)),
                ('google_ads_conversion_id', models.CharField(blank=True, help_text='Google Ads Conversion ID', max_length=20)),
                ('custom_tracking_code', models.TextField(blank=True, help_text='Custom tracking code (head section)')),
                ('custom_body_code', models.TextField(blank=True, help_text='Custom tracking code (body section)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Analytics',
                'verbose_name_plural': 'Google Analytics',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('services', 'Services Page'), ('gallery', 'Gallery Page'), ('team', 'Team Page'), ('testimonials', 'Testimonials Page'), ('blog', 'Blog Page'), ('contact', 'Contact Page'), ('pricing', 'Pricing Page')], max_length=20, unique=True)),
                ('page_title', models.CharField(help_text='Page title (max 60 characters)', max_length=60)),
                ('meta_description', models.TextField(help_text='Meta description (max 160 characters)', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('h1_tag', models.CharField(blank=True, help_text='Main H1 heading', max_length=100)),
                ('h2_tag', models.CharField(blank=True, help_text='Secondary H2 heading', max_length=100)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for this page')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=60)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image', null=True, upload_to='seo/')),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter Card title', max_length=60)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter Card description', max_length=160)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card image', null=True, upload_to='seo/')),
                ('schema_markup', models.TextField(blank=True, help_text='JSON-LD structured data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
                'ordering': ['page_type'],
            },
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_palette',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='custom_accent_color',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='custom_primary_color',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='custom_secondary_color',
        ),
        migrations.CreateModel(
            name='SEOPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('services', 'Services Page'), ('gallery', 'Gallery Page'), ('team', 'Team Page'), ('testimonials', 'Testimonials Page'), ('blog', 'Blog Page'), ('contact', 'Contact Page'), ('pricing', 'Pricing Page')], max_length=20)),
                ('content_section', models.CharField(help_text="Content section (e.g., 'hero_text', 'about_intro')", max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for images', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page Content',
                'verbose_name_plural': 'SEO Page Content',
                'ordering': ['page_type', 'content_section'],
                'unique_together': {('page_type', 'content_section')},
            },
        ),
        migrations.DeleteModel(
            name='ColorPalette',
        ),
    ]
